### ISSUE TITLE
Divide by zero on system.php

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/Web#210]
Reported by @rickmastfan67

http://tm.teresco.org/user/system.php?units=miles&u=rickmastfan67&sys=usafl

Warning: Division by zero in /home/www/tm/user/system.php on line 199

I'm assuming that error shouldn't be showing up on that page?

**Comment by yakra** [comment]
I no longer see this error message on this page. Maybe it was purposefully fixed; maybe it was fixed in the process of working on something else.

Shall we close this issue?

**Comment by jteresco** [comment]
The error remains if one chooses that page for a devel system.  Let's leave it open.

**Comment by jteresco** [comment]
Better yet, I fixed it...
